services:
  duoc_usuarios:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8084:8084"
    environment:
      - spring.datasource.url=jdbc:oracle:thin:@qsyvmd9j8goanrs4_high?TNS_ADMIN=/app/oracle_wallet
      - spring.datasource.username=NATHAN_BOOKS
      - spring.datasource.password=Ys22uN5zK9NQxqB123
    command: ["java","-jar","app.jar"]
    restart: always
